const { assert, launch, login, visit, shot, fit, saved } = require('./browser-support.cjs');
const sharp = require('sharp');

(async () => {
  const browser = await launch();
  let activePage;
  try {
    for (const width of [1440, 390]) {
      const page = await browser.newPage({ viewport: { width, height: 960 } });
      activePage = page;
      page.setDefaultTimeout(20000);
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      page.on('dialog', dialog => dialog.accept());
      await page.addInitScript(() => localStorage.setItem('livraria-cloud-theme', 'dark'));
      await login(page);
      const name = `ABLE ${width} ${Date.now()}`;
      await visit(page, '/fornecedores');
      await page.getByRole('button', { name: 'Novo fornecedor', exact: true }).click();
      await page.getByLabel('Nome', { exact: true }).fill(name);
      await saved(page, '/api/referencias/fornecedores', () => page.getByRole('button', { name: 'Cadastrar', exact: true }).click());
      await visit(page, '/cadastro');
      await page.getByRole('button', { name: 'Novo livro', exact: true }).click();
      await page.getByLabel('Código de barras (EAN/ISBN)').fill(name.replaceAll(' ', '-'));
      await page.getByLabel('Título', { exact: true }).fill(name);
      await page.getByLabel('Valor (R$)').fill('20,00');
      await page.getByLabel('Estoque inicial').fill('0');
      await page.getByRole('combobox', { name: 'Categoria' }).click();
      await page.getByRole('option').first().click();
      const buffer = await sharp({ create: { width: 80, height: 120, channels: 3, background: '#4680ff' } }).png().toBuffer();
      await page.locator('input[type=file]').setInputFiles({ name: 'capa.png', mimeType: 'image/png', buffer });
      await page.getByRole('button', { name: 'Remover imagem' }).waitFor();
      await page.waitForFunction(() => [...document.images].some(i => i.alt.startsWith('Capa de') && i.naturalWidth > 0));
      await fit(page); await shot(page, `cadastro-form-${width}-dark`);
      const book = await saved(page, '/api/catalogo', () => page.getByRole('button', { name: 'Cadastrar', exact: true }).click());
      assert.ok(book.sync_uid);
      await page.getByRole('button', { name: 'Inativos', exact: true }).click();
      await page.getByPlaceholder('Título, autor ou código').fill(name);
      const row = page.getByRole('row').filter({ hasText: name });
      await row.getByTitle('Editar ou reativar').click();
      await page.getByRole('checkbox', { name: 'Ativo no catálogo e no PDV' }).check();
      await saved(page, '/api/catalogo/' + book.sync_uid, () => page.getByRole('button', { name: 'Alterar', exact: true }).click(), 'PUT');
      await page.getByRole('button', { name: 'Ativos', exact: true }).click();
      await row.getByTitle('Editar').click();
      await page.getByRole('checkbox', { name: 'Ativo no catálogo e no PDV' }).uncheck();
      await saved(page, '/api/catalogo/' + book.sync_uid, () => page.getByRole('button', { name: 'Alterar', exact: true }).click(), 'PUT');
      await visit(page, '/lancamentos');
      await page.getByRole('button', { name: 'Novo lançamento' }).click();
      const supplier = page.getByRole('combobox', { name: 'Fornecedor', exact: true });
      await supplier.fill(name);
      await page.getByRole('option', { name, exact: true }).click();
      await page.getByPlaceholder('Código, título ou autor').fill(name);
      await page.getByPlaceholder('Código, título ou autor').press('Enter');
      await page.getByLabel('Quantidade', { exact: true }).fill('30');
      await page.getByLabel('Custo (R$)', { exact: true }).fill('10,00');
      await saved(page, '/itens', () => page.getByRole('button', { name: 'Adicionar', exact: true }).click());
      await fit(page); await shot(page, `entrada-${width}-dark`);
      await saved(page, '/finalizacao', () => page.getByRole('button', { name: 'Dar entrada', exact: true }).click());
      await visit(page, '/pesquisa');
      await page.getByLabel('Título ou Autor').fill(name);
      await page.getByLabel('Título ou Autor').press('Enter');
      await page.getByText('30', { exact: true }).waitFor();
      await fit(page); await shot(page, `pesquisa-detalhe-${width}-dark`);
      await visit(page, '/inventario');
      await page.getByPlaceholder('Código, título ou autor').fill(name);
      await page.getByPlaceholder('Código, título ou autor').press('Enter');
      await page.getByRole('button', { name: 'Fechar sessão e revisar' }).click();
      await page.getByRole('button', { name: 'Aplicar ajustes' }).waitFor();
      await fit(page); await shot(page, `inventario-revisao-${width}-dark`);
      await saved(page, '/contagens', () => page.getByRole('button', { name: 'Aplicar ajustes' }).click());
      await visit(page, '/llms');
      await page.getByRole('button', { name: 'Nova LLM', exact: true }).click();
      const dialog = page.getByRole('dialog');
      await dialog.getByLabel('Nome', { exact: true }).fill(name);
      await dialog.getByLabel('Modelo', { exact: true }).fill('modelo-teste');
      await fit(page); await shot(page, `llm-dialog-${width}-dark`);
      await saved(page, '/api/llms', () => dialog.getByRole('button', { name: 'Salvar', exact: true }).click());
      await dialog.waitFor({ state: 'hidden' });
      await visit(page, '/pdvs');
      await page.getByRole('button', { name: 'Nova máquina', exact: true }).click();
      await page.getByLabel('Nome da máquina').fill(name);
      await page.getByRole('combobox', { name: 'Operador vinculado' }).click();
      await page.getByRole('option').first().click();
      await saved(page, '/api/pdvs', () => page.getByRole('button', { name: 'Cadastrar máquina', exact: true }).click());
      assert.deepEqual(errors, []);
      console.log(`Fluxos reais ${width}: fornecedor, imagem, livro zero/inativo/reativação, entrada 30x10, inventário, LLM e PDV OK`);
      await page.close();
    }
  } catch (error) { if (activePage && !activePage.isClosed()) { await shot(activePage, "fluxo-falha"); console.log((await activePage.locator("body").innerText()).slice(-1800)); } throw error; }
  finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
